package com.verbum.universalis.ui.settings

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import com.verbum.universalis.data.ssh.SSHKeyManager
import com.verbum.universalis.data.sync.GitSyncViewModel
import com.verbum.universalis.data.sync.SyncStatus
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SettingsScreen(
    gitSyncViewModel: GitSyncViewModel = hiltViewModel(),
    onBack: () -> Unit = {}
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    
    val syncStatus by gitSyncViewModel.syncStatus.collectAsState()
    
    var repoUrl by remember { mutableStateOf("") }
    var showKeyGenerated by remember { mutableStateOf(false) }
    
    // Load saved repo URL
    LaunchedEffect(syncStatus) {
        if (syncStatus.repoUrl != null) {
            repoUrl = syncStatus.repoUrl!!
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Settings") },
                navigationIcon = { 
                    Text("<", modifier = Modifier.clickable { onBack() }.padding(16.dp)) 
                }
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .padding(16.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // SSH Deploy Key Section
            Text("Git Sync (SSH Deploy Key)", style = MaterialTheme.typography.titleMedium)
            
            Card(
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Text(
                        "1. Generate SSH Key",
                        style = MaterialTheme.typography.labelMedium
                    )
                    
                    Button(
                        onClick = {
                            val sshManager = SSHKeyManager(context)
                            if (!sshManager.keyExists()) {
                                sshManager.generateKeyPair()
                                showKeyGenerated = true
                                Toast.makeText(context, "SSH key generated!", Toast.LENGTH_SHORT).show()
                            } else {
                                showKeyGenerated = true
                            }
                        },
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Text(if (showKeyGenerated) "Regenerate Key" else "Generate SSH Key")
                    }
                    
                    if (showKeyGenerated) {
                        val sshManager = SSHKeyManager(context)
                        val publicKey = sshManager.getPublicKey()
                        
                        Text(
                            "2. Copy SSH Key",
                            style = MaterialTheme.typography.labelMedium
                        )
                        
                        OutlinedTextField(
                            value = publicKey ?: "No key found",
                            onValueChange = {},
                            modifier = Modifier.fillMaxWidth(),
                            readOnly = true,
                            textStyle = MaterialTheme.typography.bodySmall.copy(
                                fontFamily = FontFamily.Monospace
                            ),
                            trailingIcon = {
                                TextButton(onClick = {
                                    publicKey?.let {
                                        copyToClipboard(context, it)
                                        Toast.makeText(context, "Copied to clipboard!", Toast.LENGTH_SHORT).show()
                                    }
                                }) {
                                    Text("Copy")
                                }
                            }
                        )
                        
                        Spacer(modifier = Modifier.height(8.dp))
                        
                        Text(
                            "3. Add to GitHub",
                            style = MaterialTheme.typography.labelMedium
                        )
                        
                        Text(
                            "Click below to open GitHub settings and add this as a Deploy Key:",
                            style = MaterialTheme.typography.bodySmall
                        )
                        
                        Button(
                            onClick = {
                                // Open GitHub deploy keys page
                                openUrl(context, "https://github.com/settings/keys")
                            },
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Text("Add Deploy Key on GitHub")
                        }
                        
                        Text(
                            "Note: Give the key 'Write' access so it can push changes.",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.error
                        )
                    }
                }
            }
            
            // Repository URL Section
            Card(
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Text(
                        "4. Enter Repo SSH URL",
                        style = MaterialTheme.typography.labelMedium
                    )
                    
                    OutlinedTextField(
                        value = repoUrl,
                        onValueChange = { repoUrl = it },
                        label = { Text("git@github.com:user/repo.git") },
                        placeholder = { Text("git@github.com:username/verbum-backup.git") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                    
                    Button(
                        onClick = {
                            if (repoUrl.isNotBlank()) {
                                gitSyncViewModel.configureRepo(repoUrl, null)
                                Toast.makeText(context, "Repo configured!", Toast.LENGTH_SHORT).show()
                            }
                        },
                        modifier = Modifier.fillMaxWidth(),
                        enabled = repoUrl.isNotBlank()
                    ) {
                        Text("Save Repo")
                    }
                }
            }
            
            // Sync Status
            Card(
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    verticalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Text("Sync Status", style = MaterialTheme.typography.titleMedium)
                    
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween
                    ) {
                        Text("Configured:")
                        Text(if (syncStatus.isConfigured) "✅ Yes" else "❌ No")
                    }
                    
                    if (syncStatus.lastSyncTime != null) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween
                        ) {
                            Text("Last sync:")
                            Text(formatTimestamp(syncStatus.lastSyncTime!!))
                        }
                    }
                    
                    if (syncStatus.errorMessage != null) {
                        Text(
                            "Error: ${syncStatus.errorMessage}",
                            color = MaterialTheme.colorScheme.error,
                            style = MaterialTheme.typography.bodySmall
                        )
                    }
                    
                    Button(
                        onClick = { gitSyncViewModel.triggerSync() },
                        modifier = Modifier.fillMaxWidth(),
                        enabled = syncStatus.isConfigured && !syncStatus.isSyncing
                    ) {
                        Text(if (syncStatus.isSyncing) "Syncing..." else "Sync Now")
                    }
                }
            }
            
            // Help text
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.surfaceVariant
                )
            ) {
                Column(modifier = Modifier.padding(16.dp)) {
                    Text("How to set up:", style = MaterialTheme.typography.titleSmall)
                    Spacer(modifier = Modifier.height(8.dp))
                    Text("1. Generate SSH key above", style = MaterialTheme.typography.bodySmall)
                    Text("2. Copy the key", style = MaterialTheme.typography.bodySmall)
                    Text("3. Go to GitHub → Settings → Deploy Keys", style = MaterialTheme.typography.bodySmall)
                    Text("4. Add New Deploy Key", style = MaterialTheme.typography.bodySmall)
                    Text("5. Paste the key and enable 'Write access'", style = MaterialTheme.typography.bodySmall)
                    Text("6. Enter your repo SSH URL above", style = MaterialTheme.typography.bodySmall)
                    Text("7. Click Save and Sync", style = MaterialTheme.typography.bodySmall)
                }
            }
        }
    }
}

private fun copyToClipboard(context: Context, text: String) {
    val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
    val clip = ClipData.newPlainText("SSH Key", text)
    clipboard.setPrimaryClip(clip)
}

private fun openUrl(context: Context, url: String) {
    try {
        val intent = android.content.Intent(android.content.Intent.ACTION_VIEW, android.net.Uri.parse(url))
        context.startActivity(intent)
    } catch (e: Exception) {
        Toast.makeText(context, "Could not open URL", Toast.LENGTH_SHORT).show()
    }
}

private fun formatTimestamp(ts: Long): String {
    val sdf = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm")
    return sdf.format(java.util.Date(ts))
}
